### ISSUE TITLE
Crossbuilder not bringing in all dependencies

### ISSUE THREAD

**Issue by padraic7a** [ubports/crossbuilder#4] opened 2018-08-20 22:18 UTC
### Description: 

Crossbuilder not bringing in all dependencies.

### Illustrations:

**Device:** Ubuntu 18.04 on the desktop. BQ M10 16.04 
**Channel:** BQ M10 rc
**Build:**

### Steps to reproduce:

run cross builder to attempt to system software as per instructions  here: https://docs.ubports.com/en/latest/appdev/system-software.html#cross-building-with-crossbuilder

### Expected behaviour:

"Crossbuilder will do everything for you: it will create the LXD container, download the development image, install all your package build dependencies, perform the build and finally, if your device is connected to your host, it will copy the packages over to the target and install them. "

### Actual behaviour:

Crossbuilder sets up the LXD container, downloads the development image and fails on installing dependencies.

### Logs and additional information:

I tried to build Libertine, then the address book.  With both I get issues with unmet dependencies. 

For libertine see full output at https://paste.ubuntu.com/p/gY9XptGJDk/
A number (>10) of dependencies are listed as follows: 

```                             Depends: python3-dbus:armhf but it is not going to be installed```

My attempt with the address book didn't show up as many errors:

```The following packages have unmet dependencies:
 builddeps:address-book-app:armhf : Depends: dh-translations:armhf but it is not installable
                                    Depends: xvfb:armhf
```

### Discussion:

Looking this one of the packages that failed to install (python3-dbus) I can see that it is available in the Ubuntu repos (https://packages.ubuntu.com/xenial/python3-dbus). 
I don't know how much bearing that has on the situation.

**Comment by mardy** [comment] 2018-08-21 12:01
Cross-compilation is different from the ordinary compilation, in that you cannot generally execute the binaries generated by the compilation in your machine, because they are made for a different architecture. So, generally when cross-compiling you don't want to execute the tests, and you can safely avoid to install all the dependencies that are related to the tests.

Please see the [debian/control file for the Online Accounts project](https://github.com/ubports/ubuntu-system-settings-online-accounts/blob/xenial/debian/control) to see how to mark the `xvfb` package as a "testing only" package. If you do something like this for the projects you are trying to build, you'll be able to build them with crossbuilder.

For `dh-translations`, unfortunately the problem is in that package itself (it should probably be marked as architecture independent, but it's not), so the workaround is to use a command I recently added to crossbuilder to specifically address such issues:

    crossbuilder inst-foreign dh-translations

This will install `dh-translations` in the container, after marking it as architecture independent.

**Comment by padraic7a** [comment] 2018-08-27 21:53
Hi Mardy, apologies for the delay in coming back to you on this. 

I followed your instructions for ```address-book-app``` and after marking

**Comment by mardy** [comment] 2018-08-28 06:10
Yes, `inst-foreign` installs the package in the container, after marking it as cross-architecture (by using the `Arch: foreign` debian option).
The error you are getting seems to be caused by the Hungarian translation:
```
[  9%] Generating hu.gmo
cd /home/padraic/address-book-app/po && /usr/bin/msgfmt -o /home/padraic/address-book-app/obj-arm-linux-gnueabihf/po/hu.gmo /home/padraic/address-book-app/po/hu.po
/home/padraic/address-book-app/po/hu.po:43: duplicate message definition...
/home/padraic/address-book-app/po/hu.po:40: ...this is the location of the first definition
/usr/bin/msgfmt: found 1 fatal error
cd /home/padraic/address-book-app/obj-arm-linux-gnueabihf/src/imports/Ubuntu/Contacts && /usr/bin/cmake -E copy /home/padraic/address-book-app/src/imports/Ubuntu/Contacts/SIMList.qml /home/padraic/address-book-app/obj-arm-linux-gnueabihf/src/imports/Ubuntu/Contacts/
[ 10%] Built target pofiles_52
make -f po/CMakeFiles/pofiles_49.dir/build.make po/CMakeFiles/pofiles_49.dir/depend
po/CMakeFiles/pofiles_55.dir/build.make:63: recipe for target 'po/hu.gmo' failed
make[3]: *** [po/hu.gmo] Error 1
```

**Comment by padraic7a** [comment] 2018-08-28 07:28
Ah that makes sense. Thanks.

If it makes sense to you I might write a quick 'Troubleshoting' section for the documentation on https://docs.ubports.com/en/latest/appdev/system-software.html#cross-building-with-crossbuilder and then close this issue.

I have one more question. Looking at my output from trying crossbuilder in libertine (https://paste.ubuntu.com/p/gY9XptGJDk/) is it accurate to say that when a package throws up an error message containing:
```but it is not installable ``` = that package should be installed with ```crossbuild foreign```
```but it is not going to be installed  ``` = that package should be marked with ```<!nocheck> in debian/control.

**Comment by mardy** [comment] 2018-08-28 09:03
I wouldn't be so categorical, I think we need to evaluate things case by case. Ideally, the latter case (`<!nocheck>`) should not happen, because when we found such cases we should fix the packaging (and I encourage you to propose a fix to the address-book-app repo :-) ). The message `is not installable` might not report the package which we need to install with `crossbuild inst-foreign` but one of the packages which depend on it. I think it would be more useful if we mentioned the most frequent cases (such as `dh_translations` and `evolution-data-server-common`), instead.

Which actually suggests me that `crossbuilder` could be made smarter and grep the `debian/control` file for `dh_translations` and other packages known to require the "foreign" treatment, and handle it all automatically...

**Comment by padraic7a** [comment] 2018-08-28 21:56
A smarter ```crossbuilder``` sounds great.

I am looking into how to report the duplicated string in the Hungarian translation. 

I am afraid that I don't know enough about packaging to be feel confident about being able to open a coherent issue on the address-book-app. I have read a few links on the Debian documentation mentioning <!nocheck> but it is all over my head.

**Comment by jonnius** [comment] 2018-09-04 17:58
I am trying to build account-plugins, getting a similar error:

```
 builddeps:account-plugins:armhf : Depends: gobject-introspection:armhf but it is not going to be installed
                                   Depends: python3:armhf but it is not going to be installed
                                   Depends: libaccount-plugin-1.0-dev:armhf (>= 0.1.9) but it is not going to be installed
                                   Depends: valac:armhf (>= 0.16) but it is not going to be installed
                                   Depends: gnome-common:armhf but it is not installable
```

Any idea on that one?

**Comment by mardy** [comment] 2018-09-04 21:08
@jonnius, I suggest you propose a merge request to the account-plugins repository (I'm the maintainer, so I'll accept it :-) ) where you remove all the Gnome/vala/introspection stuff: it's not used in unity8. And I don't see where the project is using python, I suspect that that might be removed as well. Once you do that, you'll be able to build the project with crossbuilder.

**Comment by jonnius** [comment] 2018-09-06 17:10
Cool. I'll try to understand how to strip this stuff then...

After removing those dependencies there are still two dependency issues:

- **libaccount-plugin-1.0-dev:armhf (>= 0.1.9)**: There is only 0.1.8 in xenial repos. Should I get a newer version somehow or should I tryp with 0.1.8 instead?
- **python3:armhf**: I do not understand why this one cannot be installed. How can I find out?

**Comment by mardy** [comment] 2018-09-06 19:13
I think you can remove them both, I don't think they should be needed.

**Comment by jonnius** [comment] 2018-09-07 16:00
Yey! It builds now with ubports/account-plugins#14. But jenkins is not happy with it. Is the xenial branch the preferred place or master?

**Comment by padraic7a** [comment] 2018-09-08 17:38
See the discussion above re xvfb. In debian/control you can append it with "<!nocheck>" and this will work. 
(I created an issue on the repo about it, but didn't ooen a pull request because I am not sure if it should properly happen in control or control.in)

**Comment by mardy** [comment] 2018-09-08 19:07
About `xvfb`, what @padraic7a said; about `apparmor-easyprof-ubuntu`, you can use the `inst-foreign` command to install it (though I wonder why it has such a dependency, maybe it can just be removed).

**Comment by jonnius** [comment] 2018-09-09 08:51
Thanks to both of you. Simply removing `apparmor-easyprof-ubuntu` was not possible. It seems the build process depends on a template in that package. But installing via `inst-foreign` worked well.

Unfortunately I still get a build error with dh_install (ubports/messaging-app#43). Could you maybe take a look on that, too, @mardy?

**Comment by mardy** [comment] 2018-09-27 19:37
There's a bug in the debian tools, that makes it so that if you define the `override_dh_auto_test` target, then it doesn't consider the `nocheck` build option. Therefore you need to write:
```
override_dh_auto_test:
ifeq (,$(findstring nocheck,$(DEB_BUILD_OPTIONS)))
	python3 -m flake8 .
        ...
endif
```

**Comment by jonnius** [comment] 2018-09-28 18:57
Thanks for helping me again, @mardy. Could you please review ubports/keyboard-component#47?

**Comment by jonnius** [comment] 2018-10-06 11:54
Here is our next candidate: [ubports/indicator-display](https://github.com/ubports/indicator-display) (does not allow issues over there):
```
 builddeps:indicator-display:armhf : Depends: lcov:armhf but it is not installable
                                     Depends: libqtdbusmock1-dev:armhf but it is not going to be installed
                                     Depends: cppcheck:armhf but it is not going to be installed
                                     Depends: dh-translations:armhf but it is not installable
```
`dh-translations` and `lcov` can be "foreign-installed". But `cppcheck` and `libqtdbusmock1-dev` apparently cannot. They are both needed for tests. So may we just remove them and disable tests? Or do you have a better idea, @mardy? Btw, could you explain why those packages are not installable, even though they are in the ubuntu repos?

**Comment by mardy** [comment] 2018-10-06 12:15
I think we should use `inst-foreign` with `dh-translations`, while the other three should have the `<!nocheck>` attribute set in the debian/control. Now I cannot investigate more, but later I'll try to understand what is preventing them from being installed.

**Comment by jonnius** [comment] 2018-10-12 18:10
Thanks again. And here we go... Could have a look at this one? ubports/indicator-display#1

**Comment by mymike00** [comment] 2018-10-14 07:40
trying to build [system-settings](https://github.com/ubports/system-settings)
I had to manually `inst-foreign`:

1. `dh-migrations`
2. `python3-pep8` and only after this one `pep8` as it depends on the first one (if you tried to install `pep8` first, please remove the `foreign/` dir in your project and install `python3-pep8` first)
3. `python3-xdg`

also `xvfb` gave me errors while compiling and I tried to `inst-foreign` it also but I got
```
dpkg-deb: error: parsing file 'tmp/DEBIAN/control' near line 35 package 'xvfb':
 duplicate value for 'Multi-Arch' field
```
but after installing all the other deps it didn't complain anymore about `xvfb` idk why...

**Comment by mardy** [comment] 2018-10-14 11:12
Hi @mymike00! Yes, indeed we should clear the `foreign/` directory! I'll work on that.

As for the system-settings, can you please cherry-pick [this](https://github.com/mardy/system-settings/commit/0e493fdda0500a6343a39de8498dd1489bedc744) into your branch and see if that works for you?

**Comment by mardy** [comment] 2018-10-14 11:19
Mmm... it seems that the `foreign` directory is already been cleared. The problem with xvfb is that you shouldn't install it in this way. I guess it should be mentioned in the `debian/control` as `xvfb:native`, as we want to run it on the host; but since it's only needed for testing, the most practical solution is to mark is as `<!nocheck>`, as in the commit I pointed you to.

**Comment by mymike00** [comment] 2018-10-14 17:20
Thanks @mardy. actually I can build that app without problems but I'll may try your fork
about `xvfb` I don't really know what happened, I tried to install it and it failed but then it didn't said anymore it was a missing deps...

**Comment by UniversalSuperBox** [comment] 2018-11-10 04:03
Am I correct to say that the original problem has been resolved, and is an issue with the package rather than Crossbuilder itself?

**Comment by mardy** [comment] 2018-11-13 15:14
@UniversalSuperBox You are, thanks for reminding me of closing this bug :-)

**Closed by mardy** 2018-11-13 15:14 UTC
